###
GET http://localhost:8080/all



###
POST http://localhost:8080/add
Content-Type: application/json

{
  "id": 10,
  "firstName": "masha",
  "secondName": "mashkina",
  "age": 50
}


###
GET http://localhost:8080/personById/1



###
GET http://localhost:8080/personByName/ivanov


###
GET http://localhost:8080/nested/inlined1/test1

###
GET http://localhost:8080/nested/inlined2/test2

###
GET http://localhost:8080/inlined/test1

###
GET http://localhost:8080/inlined/test2

###
GET http://localhost:8080/inlined/test3
###